import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

/**
 * Where uploaded files live.
 *
 * Behind an interface with one local implementation, so moving to S3 later is
 * a new class rather than a hunt through the codebase for `fs` calls. No AWS
 * dependency is added for a feature that does not need one yet -- the seam is
 * the point, not the abstraction for its own sake.
 */
export interface StoredObject {
  /** Opaque key. Callers store it and hand it back; they must not parse it. */
  key: string;
  sizeBytes: number;
}

export interface ObjectStorage {
  put(bytes: Buffer, extension: string): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

export class LocalDiskStorage implements ObjectStorage {
  constructor(private readonly root: string) {}

  async put(bytes: Buffer, extension: string): Promise<StoredObject> {
    // Random name, never the uploader's. A client-supplied filename is a path
    // traversal waiting to happen, and two brands uploading "banner.png" must
    // not collide.
    const key = `${crypto.randomBytes(16).toString('hex')}.${extension}`;
    const target = this.resolve(key);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, bytes);
    return { key, sizeBytes: bytes.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    return fs.readFile(this.resolve(key));
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolve(key), { force: true });
  }

  /**
   * Refuses to resolve outside the storage root.
   *
   * Keys are generated by us, so in theory this cannot trigger. In practice
   * "this value is always safe" stops being true the first time someone adds
   * a code path that passes a key in from elsewhere, and by then the check is
   * missing.
   */
  private resolve(key: string): string {
    const target = path.resolve(this.root, key);
    const root = path.resolve(this.root);
    if (target !== root && !target.startsWith(root + path.sep)) {
      throw new Error('Refusing to resolve a storage key outside the root');
    }
    return target;
  }
}
